FROM centos:7

MAINTAINER kissofjudase23@gmail.com

RUN yum -y update
RUN yum -y install yum-utils
RUN yum -y groupinstall development

RUN yum -y install https://centos7.iuscommunity.org/ius-release.rpm
RUN yum -y install python35u
RUN yum -y install python35u-pip

RUN pip3.5 install numpy

