FROM ubuntu:16.04

MAINTAINER kissofjudase23@gmail.com

RUN apt-get -y update
RUN apt-get -y install python3.5
RUN apt-get -y install python3-pip

RUN pip3 install pip==9.0.1
RUN pip3 install numpy
RUN pip3 install nose
RUN pip3 install coverage

