FROM centos:6

LABEL author="kissofjudase23@gmail.com"

RUN yum update -y && yum install -y \
    epel-release-6 \
    gcc-c++ \
    python-setuptools \
    util-linux-ng

RUN easy_install pip

RUN pip install pip==9.0.1 \
    nose \
    coverage

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["/bin/bash"]



