FROM centos:7

LABEL author="kissofjudase23@gmail.com"

RUN yum update -y && yum install -y \
    epel-release-7 \
    python34-setuptools \

RUN easy_install-3.4 pip

RUN pip3.4 install \
    coverage \
    nose \
    numpy

# for python3.5
#RUN yum install -y https://centos7.iuscommunity.org/ius-release.rpm \
#    python35u \
#    python35u-pip

#RUN pip3.5 install \
#    coverage \
#    nose \
#    numpy

